const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  //
  GET_IMAGE_LIMIT: "GET_IMAGE_LIMIT",
  GET_OCR_LIMIT:"GET_OCR_LIMIT",
  SEGMENT_SEARCH:"SEGMENT_SEARCH",
  IMAGE_SEARCH:"IMAGE_SEARCH",
  OBJECT_DETECTION: "OBJECT_DETECTION",

  SUBMIT_PATH: 'SUBMIT_PATH'
};

export default actionTypes;
